# Generated by Django 3.0.5 on 2022-03-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firts_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
