# Generated by Django 4.0.2 on 2022-03-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_state_shippingaddress_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
